In [1]:
import pandas as pd
from scipy import stats

In [2]:
df = pd.read_csv("Amazon_Sales_Cleaned_data.csv")
df

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,...,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by,mon,month,revenue
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,T-shirt,S,On the Way,...,647.62,MUMBAI,MAHARASHTRA,400081,IN,False,Easy Ship,Apr,2022-04,647.62
1,1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,3XL,Shipped,...,406.00,BENGALURU,KARNATAKA,560085,IN,False,Easy Ship,Apr,2022-04,406.00
2,2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,...,329.00,NAVI MUMBAI,MAHARASHTRA,410210,IN,True,Easy Ship,Apr,2022-04,329.00
3,3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,Blazzer,L,On the Way,...,753.33,PUDUCHERRY,PUDUCHERRY,605008,IN,False,Easy Ship,Apr,2022-04,753.33
4,4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,Trousers,3XL,Shipped,...,574.00,CHENNAI,TAMIL NADU,600073,IN,False,Easy Ship,Apr,2022-04,574.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128936,128970,406-6001380-7673107,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,...,517.00,HYDERABAD,TELANGANA,500013,IN,False,Easy Ship,May,2022-05,517.00
128937,128971,402-9551604-7544318,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,T-shirt,M,Shipped,...,999.00,GURUGRAM,HARYANA,122004,IN,False,Easy Ship,May,2022-05,999.00
128938,128972,407-9547469-3152358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,Blazzer,XXL,Shipped,...,690.00,HYDERABAD,TELANGANA,500049,IN,False,Easy Ship,May,2022-05,690.00
128939,128973,402-6184140-0545956,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XS,Shipped,...,1199.00,Halol,GUJARAT,389350,IN,False,Easy Ship,May,2022-05,1199.00
128940,128974,408-7436540-8728312,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,T-shirt,S,Shipped,...,696.00,Raipur,CHHATTISGARH,492014,IN,False,Easy Ship,May,2022-05,696.00

In [3]:
df.drop(['month', 'revenue'], axis = 1, inplace = True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128941 entries, 0 to 128940
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128941 non-null  int64
 1   Order ID            128941 non-null  object
 2   Date                128941 non-null  object
 3   Status              128941 non-null  object
 4   Fulfilment          128941 non-null  object
 5   Sales Channel       128941 non-null  object
 6   ship-service-level  128941 non-null  object
 7   Category            128941 non-null  object
 8   Size                128941 non-null  object
 9   Courier Status      128941 non-null  object
 10  Qty                 128941 non-null  int64
 11  currency            128941 non-null  object
 12  Amount              128941 non-null  float64
 13  ship-city           128941 non-null  object
 14  ship-state          128941 non-null  object
 15  ship-postal-code    128941 non-null  int64
 16  ship-country        128941 non-null  object
 17  B2B                 128941 non-null  bool
 18  fulfilled-by        128941 non-null  object
 19  mon                 128941 non-null  object
dtypes: bool(1), float64(1), int64(3), object(15)
memory usage: 18.8+ MB

In [12]:
df.mon.unique()

array(['Apr', 'Mar', 'May', 'Jun'], dtype=object)

In [13]:
df.groupby('ship-state')['Amount'].agg(['sum', 'mean', 'median', 'std', 'count'])

                           sum        mean  median         std  count
ship-state
ANDAMAN & NICOBAR    165894.62  648.025859  615.50  262.142171    256
ANDHRA PRADESH      3444734.86  634.740162  605.00  279.988055   5427
APO                     605.00  605.000000  605.00         NaN      1
ARUNACHAL PRADESH    102500.00  697.278912  664.00  261.667581    147
ASSAM               1088229.20  653.983894  605.00  274.374393   1664
BIHAR               1505236.32  712.369295  657.00  301.571229   2113
CHANDIGARH           221468.67  663.079850  625.50  276.581990    334
CHHATTISGARH         596816.83  656.564169  605.00  275.744222    909
DADRA AND NAGAR       46978.92  671.127429  605.00  270.824812     70
GOA                  671903.85  590.944459  549.00  245.152411   1137
GUJARAT             2929545.82  653.624681  605.00  260.238580   4482
HARYANA             3017085.99  684.146483  625.00  289.876095   4410
HIMACHAL PRADESH     542543.51  687.634360  635.00  298.363327    789
JAMMU & KASHMIR      489058.74  696.664872  635.00  294.975349    702
JHARKHAND            983093.21  674.737962  614.00  281.791104   1457
KARNATAKA          11045764.22  637.598951  605.00  265.518940  17324
KERALA              4086129.58  621.275594  605.00  243.399648   6577
LADAKH                38993.43  906.823953  824.00  320.246954     43
LAKSHADWEEP            3175.29  793.822500  798.00   50.517845      4
MADHYA PRADESH      1692463.98  668.429692  605.00  278.713224   2532
MAHARASHTRA        14059073.05  631.244300  605.00  265.006460  22272
MANIPUR              221060.99  704.015892  654.00  296.476799    314
MEGHALAYA            125921.81  608.317923  569.00  253.659599    207
MIZORAM               43763.71  575.838289  543.45  186.175274     76
NAGALAND             148080.67  791.875241  735.00  344.582168    187
NEW DELHI           4635882.41  658.132085  605.00  275.546033   7044
ODISHA              1471599.39  687.984755  626.00  299.272324   2139
PONDICHERRY             529.00  529.000000  529.00         NaN      1
PUDUCHERRY           205500.24  590.517931  540.95  240.237834    348
PUNJAB              1281468.89  667.084274  605.00  299.219794   1921
RAJASTHAN           1872233.16  688.321015  625.00  305.757326   2720
SIKKIM               149903.66  731.237366  696.00  264.782201    205
TAMIL NADU          6927557.30  603.025531  563.00  255.915768  11488
TELANGANA           7334888.08  647.386415  605.00  270.383957  11330
TRIPURA               98598.40  652.969536  605.00  261.074930    151
UTTAR PRADESH       7241397.08  680.198862  625.00  288.074257  10646
UTTARAKHAND         1039765.55  669.952030  605.00  285.672301   1552
WEST BENGAL         3758892.82  630.475146  599.00  262.568828   5962

In [7]:
df[['Qty', 'Amount']].corr()

             Qty    Amount
Qty     1.000000  0.071385
Amount  0.071385  1.000000

In [15]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by,mon
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,T-shirt,S,On the Way,0,INR,647.62,MUMBAI,MAHARASHTRA,400081,IN,False,Easy Ship,Apr
1,1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,3XL,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085,IN,False,Easy Ship,Apr
2,2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210,IN,True,Easy Ship,Apr
3,3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,Blazzer,L,On the Way,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008,IN,False,Easy Ship,Apr
4,4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,Trousers,3XL,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073,IN,False,Easy Ship,Apr

In [27]:
test1 = stats.ttest_ind(df.Amount, df['Order ID'].count())
z_stat, p_value = test1.statistic, test1.pvalue
print(f"t-statistic: {z_stat}")
print(f"P_value: {p_value}")

t-statistic: -470.35853565459513
P_value: 0.0

In [28]:
df.Amount.mean()

np.float64(645.941463537587)

In [30]:
mu = df.Amount.mean() # Hypothesized mean
alpha = 0.05  # Significance level

test = stats.ttest_1samp(df.Amount, mu)
t_stat, p_value = test.statistic, test.pvalue

print(f"t-statistic: {t_stat:.6f}")
print(f"p-value: {p_value:.6f}")
print(f"df: {test.df}")

t-statistic: 0.000000
p-value: 1.000000
df: 128940